//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFolderResult {
            get {
                return ((string)(this["TextPathFolderResult"]));
            }
            set {
                this["TextPathFolderResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileWordUdostovereniyeTemplate {
            get {
                return ((string)(this["TextPathFileWordUdostovereniyeTemplate"]));
            }
            set {
                this["TextPathFileWordUdostovereniyeTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileWordEvidenceTemplate {
            get {
                return ((string)(this["TextPathFileWordEvidenceTemplate"]));
            }
            set {
                this["TextPathFileWordEvidenceTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileWordStatementTemplate {
            get {
                return ((string)(this["TextPathFileWordStatementTemplate"]));
            }
            set {
                this["TextPathFileWordStatementTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathResulInputForParallelFolder {
            get {
                return ((string)(this["TextPathResulInputForParallelFolder"]));
            }
            set {
                this["TextPathResulInputForParallelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileWordCertificateDGTemplate {
            get {
                return ((string)(this["TextPathFileWordCertificateDGTemplate"]));
            }
            set {
                this["TextPathFileWordCertificateDGTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileExcelDataStudentsUdostovereniye {
            get {
                return ((string)(this["TextPathFileExcelDataStudentsUdostovereniye"]));
            }
            set {
                this["TextPathFileExcelDataStudentsUdostovereniye"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileExcelDataStudentsForStatement {
            get {
                return ((string)(this["TextPathFileExcelDataStudentsForStatement"]));
            }
            set {
                this["TextPathFileExcelDataStudentsForStatement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string TextPathFileExcelDataStudentsForCertificateDG {
            get {
                return ((string)(this["TextPathFileExcelDataStudentsForCertificateDG"]));
            }
            set {
                this["TextPathFileExcelDataStudentsForCertificateDG"] = value;
            }
        }
    }
}
