//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFolderResult {
            get {
                return ((string)(this["PathFolderResult"]));
            }
            set {
                this["PathFolderResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFileWordUdostovereniyeTemplate {
            get {
                return ((string)(this["PathFileWordUdostovereniyeTemplate"]));
            }
            set {
                this["PathFileWordUdostovereniyeTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFileWordEvidenceTemplate {
            get {
                return ((string)(this["PathFileWordEvidenceTemplate"]));
            }
            set {
                this["PathFileWordEvidenceTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFileWordStatementTemplate {
            get {
                return ((string)(this["PathFileWordStatementTemplate"]));
            }
            set {
                this["PathFileWordStatementTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathResulInputForParallelFolder {
            get {
                return ((string)(this["PathResulInputForParallelFolder"]));
            }
            set {
                this["PathResulInputForParallelFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFileWordCertificateDGTemplate {
            get {
                return ((string)(this["PathFileWordCertificateDGTemplate"]));
            }
            set {
                this["PathFileWordCertificateDGTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFileExcelDataStudents {
            get {
                return ((string)(this["PathFileExcelDataStudents"]));
            }
            set {
                this["PathFileExcelDataStudents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбери свой путь")]
        public string PathFileWordCertificate12DGTemplate {
            get {
                return ((string)(this["PathFileWordCertificate12DGTemplate"]));
            }
            set {
                this["PathFileWordCertificate12DGTemplate"] = value;
            }
        }
    }
}
